# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=30)),
                ('bio', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='Buyers')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
    ]
