# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20180616_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_profile',
            name='user',
        ),
    ]
