# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20180617_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer_profile',
            new_name='Buyer',
        ),
    ]
